import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div className="prose">
          <h1>Loop Pedal Online</h1>
        </div>
        {children}
      </body>
    </html>
  );
}
